version: "3"

services:
  meli-traceip-app:
    container_name: meli-traceip-app
    image: nestjs-api-meli-traceip
    command: npm run start:dev
    build:
        context: .
        dockerfile: ./Dockerfile
    ports: 
        - 5000:5000    
    volumes:
        - ./:/app/
    restart: always          
